version: 2.1

jobs:
  test:
    docker:
      - image: cypress/included:15.4.0  # Cypress + dependencies
    working_directory: ~/project
    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install Dependencies
          command: npm install

      # Run Cypress tests directly against Lightsail
      - run:
          name: Run Cypress E2E Tests
          command: npx cypress run --headless --browser chrome

workflows:
  test_only:
    jobs:
      - test

