version: 2.1

jobs:
  test:
    docker:
      - image: cypress/base:18 # Official Cypress base image with all dependencies
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Cypress E2E Tests
          command: npx cypress run --headless --browser chrome

  deploy:
    docker:
      - image: cimg/base:2024.01
    steps:
      - add_ssh_keys:
          fingerprints:
            # Add your SSH key fingerprint here if needed
            # - "MD5:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx"
      - run:
          name: Add Server to Known Hosts
          command: ssh-keyscan -H $SERVER_HOST >> ~/.ssh/known_hosts
      - run:
          name: Deploy Application
          command: >
            ssh $SERVER_USER@$SERVER_HOST "
              APP_DIR='/var/www/nextjs-app';
              GIT_REPO='git@github.com:tunnayla01/nextjs-app-notouch.git';

              if [ -d \"\$APP_DIR/.git\" ]; then
                echo '--- Updating existing application ---';
                cd \$APP_DIR &&
                git pull origin main &&
                npm install &&
                npm run build &&
                pm2 reload nextjs-app;
              else
                echo '--- Performing initial deployment ---';
                git clone \$GIT_REPO \$APP_DIR &&
                cd \$APP_DIR &&
                npm install &&
                npm run build &&
                pm2 start ecosystem.config.js --env production &&
                pm2 save;
              fi

              echo '--- Deployment successful ---';
            "

workflows:
  test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - main

