version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/node:20.10  # Node.js environment
    working_directory: ~/project
    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install Dependencies
          command: npm install

      # Build Next.js app
      - run:
          name: Build Next.js App
          command: npm run build

      # Add SSH key (configure in CircleCI Project Settings)
      - add_ssh_keys:
          fingerprints:
            # Add your Lightsail SSH key fingerprint here
            # - "MD5:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx"
            
      # Add server to known hosts
      - run:
          name: Add server to known hosts
          command: ssh-keyscan -H $SERVER_HOST >> ~/.ssh/known_hosts

      # Deploy to Lightsail
      - run:
          name: Deploy Next.js App
          command: >
            ssh $SERVER_USER@$SERVER_HOST "
              APP_DIR='/var/www/nextjs-app-notouch';
              GIT_REPO='git@github.com:tunnayla01/nextjs-app-notouch.git';

              if [ -d \"\$APP_DIR/.git\" ]; then
                echo '--- Pulling latest changes ---';
                cd \$APP_DIR &&
                git reset --hard &&
                git pull origin main &&
                npm install &&
                npm run build &&
                pm2 reload nextjs-app;
              else
                echo '--- First-time deployment ---';
                git clone \$GIT_REPO \$APP_DIR &&
                cd \$APP_DIR &&
                npm install &&
                npm run build &&
                pm2 start ecosystem.config.js --env production &&
                pm2 save;
              fi
              echo '--- Deployment successful ---';
            "

workflows:
  build_and_deploy:
    jobs:
      - deploy

