version: 2.1

jobs:
  test:
    docker:
      - image: cypress/included:15.4.0  # Cypress with all dependencies preinstalled
    working_directory: ~/project
    steps:
      - checkout

      # Restore cached node_modules
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-

      # Install project dependencies
      - run:
          name: Install Dependencies
          command: npm install

      # Save cache for node_modules
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      # Build the Next.js app
      - run:
          name: Build Next.js App
          command: npm run build

      # Start Next.js server in the background
      - run:
          name: Start Next.js server
          command: npm run start &

      # Wait until the server is ready
      - run:
          name: Wait for server
          command: npx wait-on http://localhost:3000

      # Restore Cypress cache
      - restore_cache:
          keys:
            - v1-cypress-{{ checksum "package-lock.json" }}
            - v1-cypress-

      # Run Cypress tests headlessly
      - run:
          name: Run Cypress E2E Tests
          command: npx cypress run --headless --browser chrome

      # Save Cypress cache
      - save_cache:
          paths:
            - ~/.cache/Cypress
          key: v1-cypress-{{ checksum "package-lock.json" }}

workflows:
  test_only:
    jobs:
      - test

